apiVersion: v1
kind: Service
metadata:
  name: {{ include "simple-dsl-web.fullname" . }}
  labels:
    {{- include "simple-dsl-web.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9292
      protocol: TCP
      name: http
  selector:
    {{- include "simple-dsl-web.selectorLabels" . | nindent 4 }}
