name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag nzjourney/simple-dsl-web:$(date +%s) && docker build . --file Dockerfile --tag nzjourney/simple-dsl-web:latest
      
    - name: Upload the Docker image to hub.docker.com
      run: docker push nzjourney/simple-dsl-web:$(date +%s) && docker push nzjourney/simple-dsl-web:latest
      
